### ISSUE TITLE
[Todo] Complete .h-files for modules

### ISSUE THREAD

**Issue by schorg** [boschresearch/blech#42]
C code generation for modules needs completion.

Related to [feature/modules](/boschresearch/blech/tree/feature/modules)

To do:
- [x] Add prototypes for exported subprograms to \<module\>.h
- [ ] Add exported constants to \<module\>.h 
- [ ] Add doc comments to entities in  \<module\>.h

**Comment by schorg** [comment]
This is still a bug in the pre-release development branch.
No code is generated for constants.
Doc comments are missing in the <module>.h file.
