### ISSUE TITLE
Remove extern information from signature

### ISSUE THREAD

**Issue by schorg** [boschresearch/blech#52]
**Describe the todo**
Signatures should not contain keyword `extern` and any C-binding annotations.

**Link to a branch**
[develop](/boschresearch/blech/tree/develop)

**Task list**
To mark completed todos, use [x]

- [ ] Filter C binding annotations
- [ ] Do not print extern in prototypes, consts and params
- [ ] Write test cases

**Comment by schorg** [comment]
This is a bad idea.
